- platform: command_line
  switches:
    desktop_pc_wol:
      command_on: !secret wol_pc_on_command
      command_off: !secret wol_pc_off_command
      friendly_name: Desktop PC

- platform: template
  switches:
    desktop_pc:
      value_template: "{{ is_state('binary_sensor.desktop_pc', 'on') }}"
      friendly_name: Desktop PC
      icon_template:  >-
        {% if is_state('binary_sensor.desktop_pc', 'on') %}
          mdi:controller-classic
        {% else %}
          mdi:controller-classic-outline
        {% endif %}
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.desktop_pc_wol
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.desktop_pc_wol

