homeassistant:
  # Name of the location where Home Assistant is running
  name: Angie
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Budapest
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant

# Enables the frontend
frontend:

# Enables configuration UI
  themes:
    day:
      primary-color: green
    night:
      # Main Stuff #
      primary-color: green # Primary (most of the UI)
      primary-background-color: "#303030" # Primary background colour (dialogs, e.t.c)
      secondary-background-color: "#303030" # Secondary background colour (main UI background)
      paper-card-background-color: "#424242" # Card background colour
      paper-item-icon-color: green # Icon colour
      primary-text-color: "#FFFFFF" # Primary text colour
      secondary-text-color: "rgba(255, 255, 255, 0.7)" # Secondary text colour
      disabled-text-color: "rgba(255, 255, 255, 0.5)" # Disabled text colour
      divider-color: "rgba(255, 255, 255, 0.12)" # Divider colour
      paper-card-header-color: "#FFFFFF" # Card header text colour

      # Nav Menu #
      paper-listbox-background-color: "#424242" # Listbox background colour
      paper-listbox-color: "#FFFFFF" # Listbox text colour
      paper-grey-200: "#616161" # Listbox selected item background colour

      # Switches #
      paper-toggle-button-checked-ink-color: green
      paper-toggle-button-checked-button-color: green
      paper-toggle-button-checked-bar-color: green

      # Sliders #
      paper-slider-knob-color: green
      paper-slider-knob-start-color: green
      paper-slider-pin-color: green
      paper-slider-active-color: green
      paper-slider-secondary-color: "#33F2D8"
      
config:
updater:

# Discover some devices automatically
discovery:

# Media players
media_player:
  - platform: mpd
    host: !secret media_player_mpd_host
    password: !secret media_player_mpd_password

telegram_bot:
  platform: polling
  api_key: !secret telegram_bot_api_key
  allowed_chat_ids:
    !secret telegram_bot_allowed_users

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# OpenUV sensors 
openuv:
  api_key: !secret openuv_api_key
  scan_interval: 1920
  binary_sensors:
    monitored_conditions:
      - uv_protection_window
  sensors:
    monitored_conditions:
      - current_ozone_level
      - current_uv_index
      - current_uv_level
      - max_uv_index
      - safe_exposure_time_type_1
      - safe_exposure_time_type_2
      - safe_exposure_time_type_3
      - safe_exposure_time_type_4
      - safe_exposure_time_type_5
      - safe_exposure_time_type_6

# Text to speech
tts:
  platform: google

google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_secret

mqtt:
  password: !secret http_password
  embedded:

alarm_control_panel:
  - platform: manual
    code: !secret alarm_code
    trigger_time: 1

group: !include groups.yaml
notify: !include_dir_merge_list notifies
automation: !include_dir_merge_list automation
sensor: !include_dir_merge_list sensors
light: !include_dir_merge_list lights
device_tracker: !include_dir_merge_list device_trackers
binary_sensor: !include_dir_merge_list binary_sensors
camera: !include_dir_merge_list camera
switch: !include_dir_merge_list switches
climate: !include_dir_merge_list climate
script: !include_dir_merge_list scripts
shell_command: !include shell_commands.yaml

