homeassistant:
  # Name of the location where Home Assistant is running
  name: Angie
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  currency: !secret currency
  time_zone: !secret time_zone
  customize: !include customize.yaml
  external_url: !secret external_url
  internal_url: !secret internal_url
  auth_providers:
    - type: homeassistant

http:
  use_x_forwarded_for: true
  trusted_proxies: !secret trusted_proxy
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

websocket_api:

# Enables the frontend
frontend:

lovelace:
  mode: yaml

system_health:

map:

config:
updater:
  reporting: false

# Discover some devices automatically
discovery:

# Media players
media_player:
  - platform: androidtv
    name: TV
    host: !secret tv_host
    turn_on_command: "input keyevent 26"
    turn_off_command: "input keyevent 26"

  - platform: androidtv
    name: kiosk_tablet
    host: !secret kiosk_tablet_host

telegram_bot:
  platform: polling
  api_key: !secret telegram_bot_api_key
  allowed_chat_ids:
    !secret telegram_bot_allowed_users

# Enables support for tracking state changes over time.
history:
# Setup recorder to use Postgresql database
recorder:
  db_url: !secret recorder_db_url
  purge_keep_days: 14

influxdb:
  host: !secret influxdb_host
  port: !secret influxdb_port
  username: !secret influxdb_user
  password: !secret influxdb_password
  database: !secret influxdb_database
  default_measurement: state
  ssl: true
  verify_ssl: true
  max_retries: 10

# View all events in a logbook
logbook:

# Track the sun
sun:
energy:
zone:
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: !secret home_radius
    icon: mdi:home

google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_secret

mqtt:
  broker: !secret mqtt_address
  password: !secret mqtt_password
  discovery: true

alarm_control_panel:
  - platform: manual
    code: !secret alarm_code
    trigger_time: 1

mobile_app:

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

notify: !include_dir_merge_list notifies
automation: !include_dir_merge_list automation
sensor: !include_dir_merge_list sensors
light: !include_dir_merge_list lights
device_tracker: !include_dir_merge_list device_trackers
binary_sensor: !include_dir_merge_list binary_sensors
camera: !include_dir_merge_list camera
switch: !include_dir_merge_list switches
climate: !include_dir_merge_list climate
script: !include_dir_merge_list scripts
shell_command: !include shell_commands.yaml
group: !include groups.yaml

