homeassistant:
  # Name of the location where Home Assistant is running
  name: Angie
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Budapest
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant

http:
  base_url: !secret base_url
  use_x_forwarded_for: true
  trusted_proxies: 
    - !secret trusted_proxy

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: yaml

system_health:

map:

config:
updater:
  reporting: false

# Discover some devices automatically
discovery:

# Media players
media_player:
  - platform: mpd
    host: !secret media_player_mpd_host
    password: !secret media_player_mpd_password

  - platform: androidtv
    name: TV
    host: !secret tv_host
    turn_on_command: "input keyevent 26"
    turn_off_command: "input keyevent 26"

telegram_bot:
  platform: polling
  api_key: !secret telegram_bot_api_key
  allowed_chat_ids:
    !secret telegram_bot_allowed_users

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# OpenUV sensors 
openuv:
  api_key: !secret openuv_api_key
  binary_sensors:
    monitored_conditions:
      - uv_protection_window
  sensors:
    monitored_conditions:
      - current_ozone_level
      - current_uv_index
      - current_uv_level
      - max_uv_index
      - safe_exposure_time_type_1
      - safe_exposure_time_type_2
      - safe_exposure_time_type_3
      - safe_exposure_time_type_4
      - safe_exposure_time_type_5
      - safe_exposure_time_type_6

google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_secret

wwlln:
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  
mqtt:
  broker: !secret mqtt_address
  password: !secret mqtt_password
  discovery: true

alarm_control_panel:
  - platform: manual
    code: !secret alarm_code
    trigger_time: 1
   
pi_hole:
  host: !secret pihole_host

group: !include groups.yaml
notify: !include_dir_merge_list notifies
automation: !include_dir_merge_list automation
sensor: !include_dir_merge_list sensors
light: !include_dir_merge_list lights
device_tracker: !include_dir_merge_list device_trackers
binary_sensor: !include_dir_merge_list binary_sensors
camera: !include_dir_merge_list camera
switch: !include_dir_merge_list switches
climate: !include_dir_merge_list climate
script: !include_dir_merge_list scripts
shell_command: !include shell_commands.yaml

