homeassistant:
  # Name of the location where Home Assistant is running
  name: Angie
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Budapest
  customize: !include customize.yaml


# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_password

updater:

# Discover some devices automatically
discovery:

# Media players
media_player:
  - platform: mpd
    host: !secret media_player_mpd_host
    password: !secret media_player_mpd_password

telegram_bot:
  platform: polling
  api_key: !secret telegram_bot_api_key
  allowed_chat_ids:
    !secret telegram_bot_allowed_users

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google

google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_secret

mqtt:
  embedded:

alarm_control_panel:
  - platform: manual
    code: !secret alarm_code
    trigger_time: 1

group: !include groups.yaml
notify: !include_dir_merge_list notifies
automation: !include_dir_merge_list automation
sensor: !include_dir_merge_list sensors
light: !include_dir_merge_list lights
device_tracker: !include_dir_merge_list device_trackers
binary_sensor: !include_dir_merge_list binary_sensors
camera: !include_dir_merge_list camera
switch: !include_dir_merge_list switches
climate: !include_dir_merge_list climate
script: !include_dir_merge_list scripts
shell_command: !include shell_commands.yaml

