homeassistant:
  # Name of the location where Home Assistant is running
  name: Angie
  # Location required to calculate the time the sun rises and sets
  # latitude: 0
  # longitude: 0
  # Impacts weather/sunrise data (altitude above sea level in meters)
  # elevation: 0
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Budapest

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_password

updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  platform: yr

# Text to speech
tts:
  platform: google

group: !include groups.yaml
