- platform: rpi_gpio_pwm
  leds:
    - name: Workstation Led strip
      driver: gpio
      pins: 26
      type: simple
- platform: rpi_gpio_pwm
  leds:
    - name: Workstation Additional Led strip
      driver: gpio
      pins: 14
      type: simple
