- platform: pi_hole
  host: !secret pihole_host
  ssl: true
  verify_ssl: true
  monitored_conditions:
    - ads_blocked_today
    - ads_blocked_today
    - dns_queries_today
    - domains_being_blocked
    - unique_clients
    - unique_domains
    - clients_ever_seen
