- platform: template
  sensors:
    yr_url:
      value_template: !secret forcast-url
    weather_url_head:
      value_template: !secret forcast-2-url-head
    weather_url_middle:
      value_template: >-
          {% if utcnow().hour <= 12 %}
            _00
          {% else %}
            _12
          {% endif %}

    weather_url_tail:
      value_template: !secret forcast-2-url-tail
