- platform: template
  sensors:
    yr_url:
      value_template: !secret forecast-url
    weather_url_head:
      value_template: !secret forecast-2-url-head
    weather_url_tail:
      value_template: !secret forecast-2-url-tail
    http_password:
      value_template: !secret http_password
