- alias: 'Trigger alarm while armed away'
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_workstation
      to: 'on'
    - platform: state
      entity_id: binary_sensor.entrance_door
      to: 'on'
    - platform: state
      entity_id: binary_sensor.living_room_door
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_away
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.ha_alarm
    - service: notify.Telegram_Notifier_To_Group
      data_template:
        message: Danger...
        data:
          video:
            - url: !secret alarm_picture
              caption: "The alarm triggered by: {{trigger.to_state.attributes.friendly_name }}"

        
- alias: 'Trigger alarm while armed night'
  trigger:
    - platform: state
      entity_id: binary_sensor.entrance_door
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_night
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.ha_alarm
    - service: notify.Telegram_Notifier_To_Group
      data_template:
        message: Danger...
        data:
          video:
            - url: !secret alarm_picture
              caption: "The alarm triggered by: {{trigger.to_state.attributes.friendly_name }}"

- alias: 'Arm alarm on leave'
  trigger:
    - platform: state
      entity_id: binary_sensor.entrance_door_lock
      to: 'on'
  condition:
    - condition: time
      before: '21:00:00'
  action:
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.ha_alarm
      data:
        code: !secret alarm_code

- alias: 'Arm alarm at night'
  trigger:
    - platform: state
      entity_id: binary_sensor.entrance_door_lock
      to: 'on'
  condition:
    - condition: time
      after: '21:00:00'
      before: '00:00:00'
  action:
    - service: alarm_control_panel.alarm_arm_night
      entity_id: alarm_control_panel.ha_alarm
      data:
        code: !secret alarm_code

- alias: 'Disarm alarm in the morning'
  trigger:
    - platform: time
      at: '07:00:00'
  condition:
    - condition: state
      entity_id: group.all_devices
      state: home
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.ha_alarm
      data:
        code: !secret alarm_code
