- alias: 'Trigger alarm while armed away'
  hide_entity: true
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_workstation
      to: 'on'
    - platform: state
      entity_id: binary_sensor.entrance_door
      to: 'on'
    - platform: state
      entity_id: binary_sensor.living_room_door
      to: 'on'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_away
    - condition: state
      entity_id: group.all_devices
      state: not_home
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.ha_alarm
    - service: notify.Telegram_Notifier_To_Group
      data_template:
        message: Danger...
        data:
          video:
            - url: !secret alarm_picture
              caption: "The alarm triggered by: {{trigger.to_state.attributes.friendly_name }}"

        
- alias: 'Trigger alarm while armed night'
  hide_entity: true
  trigger:
    - platform: state
      entity_id: binary_sensor.entrance_door_lock
      to: 'off'
    - platform: state
      entity_id: binary_sensor.entrance_door
      to: 'on'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_night
    - condition: state
      entity_id: group.all_devices
      state: not_home
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.ha_alarm
    - service: notify.Telegram_Notifier_To_Group
      data_template:
        message: Danger...
        data:
          video:
            - url: !secret alarm_picture
              caption: "The alarm triggered by: {{trigger.to_state.attributes.friendly_name }}"

- alias: 'Arm alarm on leave'
  hide_entity: true
  trigger:
    - platform: state
      entity_id: binary_sensor.entrance_door_lock
      to: 'off'
  condition:
    - condition: time
      before: '21:00:00'
  action:
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.ha_alarm
      data:
        code: !secret alarm_code

- alias: 'Arm alarm at night'
  hide_entity: true
  trigger:
    - platform: state
      entity_id: binary_sensor.entrance_door_lock
      to: 'on'
  condition:
    - condition: time
      after: '21:00:00'
      before: '00:00:00'
  action:
    - service: alarm_control_panel.alarm_arm_night
      entity_id: alarm_control_panel.ha_alarm
      data:
        code: !secret alarm_code

- alias: 'Arm alarm at daytime'
  hide_entity: true
  trigger:
    - platform: time
      at: '07:00:00'
  condition:
    - condition: state
      entity_id: group.all_devices
      state: 'not home'
  action:
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.ha_alarm
      data:
        code: !secret alarm_code
        
- alias: 'Disarm alarm in the morning'
  hide_entity: true
  trigger:
    - platform: time
      at: '07:00:00'
  condition:
    - condition: state
      entity_id: group.all_devices
      state: home
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.ha_alarm
      data:
        code: !secret alarm_code

- alias: 'Disarm alarm when somebody come home'
  hide_entity: true
  trigger:
    - platform: state
      entity_id: binary_sensor.entrance_door
      to: 'on'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: group.all_devices
      state: home
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.ha_alarm
          state: 'armed_away'
        - condition: state
          entity_id: alarm_control_panel.ha_alarm
          state: 'armed_night'
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.ha_alarm
      data:
        code: !secret alarm_code

