- alias: "Trun off all the lights when nobody is home"
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id: alarm_control_panel.ha_alarm
    to: 'armed_away'
  action:
    service: light.turn_off
    entity_id: group.all_lights
