- id: ensure_smart_devices_on
  initial_state: 'on'
  alias: 'Ensure smart-devices are on'
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.entrance_door
        - light.bedroom_ceiling_light
        - light.living_room_ceiling_light
        - sensor.thermostat_temperature
        - sensor.outside_temperature
        - sensor.gecko_tank_temperature
      to: 'unavailable'
      for: '00:05:00'
  action:
    - service: notify.mobile_app_user_1
      data_template:
        title: "Check {{ trigger.to_state.name }}"
        message: "Looks like {{ trigger.to_state.name }} is {{ trigger.to_state.state }}"
    - service: notify.telegram_notifier_to_user_1
      data_template:
        message: "Check {{ trigger.to_state.name }}\nLooks like {{ trigger.to_state.name }} is {{ trigger.to_state.state }}"

- id: ensure_door_is_closed
  initial_state: 'on'
  alias: 'Ensure entrance door closed & locked'
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.entrance_door
        - binary_sensor.entrance_door_lock
      to: 'on'
      for: '00:03:00'
  action:
    - service: notify.notify
      data_template:
        title: "Check {{ trigger.to_state.name }}"
        message: "{{ trigger.to_state.name }} is open!"
    - service: notify.telegram_notifier_to_group
      data_template:
        message: "Check {{ trigger.to_state.name }}\nLooks like {{ trigger.to_state.name }} is open!"

- alias: "Update Available Notification"
  trigger:
    - platform: state
      entity_id: binary_sensor.updater
      from: "off"
      to: "on"
  action:
    - service: notify.notify
      data:
        message: "Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version') }} is available."
