- alias: "Turn Workstation LED's on triggered by PIR"
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id: binary_sensor.pir_workstation
    from: 'off'
    to: 'on'
  condition:
    condition: sun
    after: sunset
    after_offset: "-1:00:00"
  action:
  - service: light.turn_on
    entity_id: light.workstation_led_strip
  - service: light.turn_on
    entity_id: light.workstation_additional_led_strip

- alias: "Turn Workstation LED's off triggered by PIR"
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id: binary_sensor.pir_workstation
    from: 'on'
    to: 'off'
    for:
      minutes: 3
  condition:
    condition: sun
    after: sunset
    after_offset: "-1:00:00"
  action:
  - service: light.turn_off
    entity_id: light.workstation_led_strip
  - service: light.turn_off
    entity_id: light.workstation_additional_led_strip

