- alias: 'Telegram bot start command'
  initial_state: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/start'
  action:
    - service: telegram_bot.send_message
      data_template:
        target: '{{ trigger.event.data.user_id }}'
        message: 'commands'
        keyboard:
          - '/ping, /status, /arm'
          - '/kitty, /kitty-gif, /doggo'

- alias: 'Telegram bot replies pong to ping'
  initial_state: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/ping'
  action:
    - service: notify.telegram_notifier_to_user_1
      data_template:
        message: 'Pong'

- alias: 'Telegram bot replies pong to ping in a group chat'
  initial_state: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: !secret telegram_bot_group_ping_cmd
  action:
    - service: notify.telegram_notifier_to_group
      data_template:
        message: 'Pong'

- alias: 'Telegram sends random kitty'
  initial_state: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/kitty'
  action:
  - service: notify.telegram_notifier_to_user_2
    data:
      message: Hey...
      data:
        photo:
          - url: https://thecatapi.com/api/images/get?type=jpg
            caption: Hey... here is a random Kitty for U ❤️
            
  - service: notify.telegram_notifier_to_user_1
    data:
      message: "Random Kitty sent \U0001F609"
        
- alias: 'Telegram sends random kitty gif'
  initial_state: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/kitty-gif'
  action:
  - service: notify.telegram_notifier_to_user_2
    data:
      message: Hey...
      data:
        video:
          - url: https://thecatapi.com/api/images/get?type=gif
            caption: Hey... here is a random Kitty for U ❤️

  - service: notify.telegram_notifier_to_user_1
    data:
      message: "Random Kitty sent \U0001F609"

- alias: 'Telegram sends random doggo'
  initial_state: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/doggo'
  action:
  - service: shell_command.get_dog_api_image
  - service: notify.telegram_notifier_to_user_2
    data:
      message: Hey...
      data:
        photo:
          - url: https://{{states.sensor.dog_api_image.state}}
            caption: Hey... here is a random Doggo for U ❤️
            
  - service: notify.telegram_notifier_to_user_1
    data:
      message: "Random Doggo sent \U0001F609"
      
- alias: 'Telegram bot notifies when golden hour approaches'
  initial_state: false
  trigger:
    platform: sun
    event: sunset
    offset: "-01:30:00"
  condition:
    condition: numeric_state
    entity_id: sensor.yr_symbol
    above: 0
    below: 4
  action:
  - service: notify.telegram_notifier_to_user_2
    data_template:
      message: Hey...
      data:
        photo:
        - url: "{{ states.sensor.reddit_sunset_image.state }}"
          caption: "The golden hour approaches!\nTake some *badass* pictures \U0001F60E \U0001F4F7 \nToday the Sun will set at: {{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom('%H:%M:%S') }}"

  - service: notify.telegram_notifier_to_user_1
    data:
      message: "Golden hour notification sent \U0001F609"

- alias: 'Telegram bot replies the alarm status'
  initial_state: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: /status
  action:
    - service: telegram_bot.send_message
      data_template:
        target: '{{ trigger.event.data.user_id }}'
        message: 'Alarm status: *{{ states.alarm_control_panel.ha_alarm.state }}*'

- alias: 'Telegram bot arms the alarm'
  initial_state: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: /arm
  action:
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.ha_alarm
      data:
        code: !secret alarm_code
    - service: telegram_bot.send_message
      data_template:
        target: '{{ trigger.event.data.user_id }}'
        message: 'Alarm armed, Alarm status: *{{ states.alarm_control_panel.ha_alarm.state }}*'

- alias: 'Telegram bot sends alert when the Heater is on and the Door is open.'
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.living_room_door
    to: 'on'
    for:
      hours: 0
      minutes: 10
      seconds: 0
  condition:
    condition: state
    entity_id: switch.living_room_heater
    state: 'on'
  action:
    - service: notify.telegram_notifier_to_group
      data_template:
        message: "The heater is on, please close the door."

- alias: 'Telegram bot sends alert when Peidl.net HTTP response code Sensor state changed.'
  initial_state: true
  trigger:
  - platform: numeric_state
    entity_id: sensor.peidl_net_status
    above: 200
  action:
    - service: notify.telegram_notifier_to_user_1
      data_template:
        message: "https://peidl.net HTTP response code changed!\nStatus code: *{{ states.sensor.peidlnet_status.state }}*"

- alias: 'Telegram bot sends alert when external ip changed.'
  initial_state: true
  trigger:
  - platform: state
    entity_id: sensor.external_ip
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ trigger.from_state.state != 'unknown' }}"
      - condition: template
        value_template: "{{ trigger.from_state.state != 'unavailable' }}"
      - condition: template
        value_template: "{{ states.sensor.external_ip.state != 'unknown' }}"
      - condition: template
        value_template: "{{ states.sensor.external_ip.state != 'unavailable' }}"
  action:
    - service: notify.telegram_notifier_to_user_1
      data_template:
        message: "External ip changed to: *{{ states.sensor.external_ip.state }}*"

- id: '1618778891001'
  alias: Washing machine has finished
  description: ''
  use_blueprint:
    path: sbyx/notify-or-do-something-when-an-appliance-like-a-dishwasher-or-washing-machine-finishes.yaml
    input:
      power_sensor: sensor.washing_machine_wattage
      actions:
      - service: notify.telegram_notifier_to_group
        data:
          message: Washing machine has finished! 💧👕

- id: '1622815331224'
  alias: Dishwasher has finished
  description: ''
  use_blueprint:
    path: sbyx/notify-or-do-something-when-an-appliance-like-a-dishwasher-or-washing-machine-finishes.yaml
    input:
      power_sensor: sensor.dishwasher_switch_wattage
      actions:
      - service: notify.telegram_notifier_to_group
        data:
          message: Dishwasher has finished! 🍽🧽

- alias: Owen preheat
  description: ''
  use_blueprint:
    path: sbyx/notify-or-do-something-when-an-appliance-like-a-dishwasher-or-washing-machine-finishes.yaml
    input:
      power_sensor: sensor.oven_switch_wattage
      actions:
      - service: notify.telegram_notifier_to_group
        data:
          message: The owen is ready & preheated! ♨️🔥

- alias: Tag Entrance door is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 09338c6e-ed2b-4507-8c6e-dc4f20109651
  condition: []
  action:
  - service: notify.telegram_notifier_to_user_1
    data:
      message: asfd
      title: asddd
  mode: single
