- alias: 'Set dark theme for the night'
  initial_state: true
  hide_entity: true
  trigger:
    - platform: time
      at: '19:00'
  action:
    - service: frontend.set_theme
      data:
        name: night
        
- alias: 'Set normal theme for the day'
  initial_state: true
  hide_entity: true
  trigger:
    - platform: time
      at: '07:00'
  action:
    - service: frontend.set_theme
      data:
        name: day

