name: Docker CI

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
      - release/*
  schedule:
    - cron: "0 5 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pull docker image
      run: docker pull homeassistant/home-assistant 
    - name: Create secrets.yaml
      run: mv secrets-example.yaml secrets.yaml
    - name: Check configuration
      run: docker run --rm -v $(pwd):/config homeassistant/home-assistant hass -c . --script check_config --files --secrets
