---
name: Python CI

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
      - release/*
  schedule:
    - cron: "0 5 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install homeassistant
      - name: Create secrets.yaml
        run: mv secrets-example.yaml secrets.yaml
      - name: Check configuration
        run: hass -c . --script check_config --files --secrets
